### ISSUE TITLE
feedback-tool screenshots do not capture the full viewport

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/project-monitoring-app#296] opened 2020-07-31 09:54 UTC
- [x] Investigate why this is happening -> it seems default value `scale: 1.25` (at least in Linux) is related 
- [x] Test in Linux
- [x] Test in Windows

**Comment by adrianq** [comment] 2020-09-03 22:15
Waiting for PR in project monitoring to close this issue

**Comment by tokland** [comment] 2020-09-04 11:43
Added in this PR: https://github.com/EyeSeeTea/project-monitoring-app/pull/303

**Comment by SferaDev** [comment] 2020-09-07 07:21
During the weekend I've been playing around on my spare time with ``html2canvas``.

- The default scale comes from the viewport of the browser so it does not even depend completely on the OS but on the device/OS/browser. Making it default to 1 is a good solution.

- The ``svg`` loading is indeed a problem, the ``allowTaint`` option is not respected anymore in the code. Doing the replacement before and restoring after should work though.

- The iframe screenshot was supported on older versions before ``1.0.0-rc.1``. I tried adding it back to the mix in the latest release but they did a rewrite from flow to typescript and most of their legacy code doesn't work without rewriting the support.

  - In any case they still have a weird bug that makes the ``iframe`` to not render correctly. I debugged and traced the root of the bug but was unable to solve it. It appears that when traversing the tree and cloning the nodes they change (without that intention) the ``node.ownerDocument`` from the iframe's document to the main window document. When doing this all the relative urls that the page contains either in scripts/css/img are broken and it fails to represent the correct HTML.

The root cause it's traced to the following lines:

```
// clone still has correct document attached (check baseURI)
            for (let child = node.firstChild; child; child = child.nextSibling) {
                if (
                    !isElementNode(child) ||
                    (!isScriptElement(child) &&
                        !child.hasAttribute(IGNORE_ATTRIBUTE) &&
                        (typeof this.options.ignoreElements !== 'function' || !this.options.ignoreElements(child)))
                ) {
                    if (!this.options.copyStyles || !isElementNode(child) || !isStyleElement(child)) {
                        // The resulting node of this.cloneNode(child) has the top window document attached
                        // AppendChild call mutates the attached document on clone
                        clone.appendChild(this.cloneNode(child));
                    }
                }
            }
// clone does not have the correct document attached (check baseURI)
```

**Closed** 2020-09-15 22:21 UTC
